
services:

  backend:
      build: ./soruce_code/
      networks:
        - e-commernce-backend-net
      expose:
        - 8080
      ports:
        - target: 8080
          host_ip: 127.0.0.1
          published: 8080
      env_file:
        - required: true
          path: ./soruce_code/backend.env
  db-sql-service:
    image: mysql:8.4
    expose:
        - 3306
    ports:
        - host_ip: 127.0.0.1
          published: 3306
          target: 3306
    networks:
        - e-commernce-backend-net

    env_file:
        - required: true
          path: ./db-sql/db-sql.env
    volumes:
        - target: /var/lib/mysql
          source: e-commerce-sql
          type: volume

        - type: bind
          source: ./db-sql/db-init
          target: /docker-entrypoint-initdb.d
          read_only: true

  caching-redis-service:
    image: redis:8.8
    expose:
      - 6379
    env_file:
      - required: true
        path: ./soruce_code/backend.env

    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
    networks:
      - e-commernce-backend-net



  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'

    networks:
      - e-commernce-backend-net
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
      - '127.0.0.1:443:443' # LocalStack HTTPS Gateway

    env_file:
          - required: true
            path: ./localStack.env
    environment:

      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - './localStack-init-scripts/:/etc/localstack/init/ready.d'
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  e-commernce-backend-net:

volumes:
    e-commerce-sql:


