package com.ecommerce.entities.user;

import jakarta.persistence.*;
import org.hibernate.annotations.ColumnDefault;

import java.sql.Timestamp;

@Entity
@Table(name="admin")
@PrimaryKeyJoinColumn(name = "admin_id" , referencedColumnName = "usr_id")
@DiscriminatorValue(value = "admin")
public class Admin extends User {

    private Timestamp lastLogin; // application level update it
    private Timestamp updated_at; // auto generated by databas triggers
    private Timestamp created_at; // auto generated by database triggers

    @Override
    public UserRoles getRole() {
        return UserRoles.ADMIN;
    }

    public Admin() {
        super();
    }

    public Timestamp getLastLogin() {
        return lastLogin;
    }

    public Timestamp getUpdated_at() {
        return updated_at;
    }

    public Timestamp getCreated_at() {
        return created_at;
    }
}
